#!/bin/sh

if [ -z "$1" ]; then
    echo 'Uh-oh...Something went wrong. Recived an invalid option'
    echo 'Usage: build_dependencies [OPTION]'
    echo "OPTIONS:"
    echo "   armv7l - (Linaro gnueabihf)"
    echo
    echo "   clean (clean the build environment)"
    echo 'Example: ./build_dependencies armv7l'
    echo
    exit 1
elif [ $1 = "clean" ]; then   
    echo "#############################"
    echo "#  Cleaning previous Build  #"
    echo "#############################"
    rm -Rfv ./code
    rm -Rfv ./output
    rm -Rfv ./toolchain
    . ./config/cleanupenv.sh
    unset CWD
    exit 1
else
    BUILD=$1
fi

### Set build location
export CWD=$PWD

echo "################################"
echo "#  Creating build environment  #"
echo "################################"

### Setup Dirs
mkdir -p code
mkdir -p dl
mkdir -p output
mkdir -p output/lib
mkdir -p output/lib/multiarch
mkdir -p toolchain

### Configure ARCH
. config/$BUILD

### Build cross compile environment
. build/python


if [ ! -f $CWD/code/.Cheetah ]; then
    cd $CWD
    echo "######################"
    echo "#  Building Cheetah  #"
    echo "######################"
    if [ ! -f $CWD/code/.Python-host ]; then
        . build/python
    fi
    . build/cheetah
    cp -avr $CWD/code/Cheetah-2.4.4/build/lib.linux-armv7l-2.7/Cheetah $CWD/output/lib/
    mv -vf $CWD/output/lib/Cheetah/_namemapper.so $CWD/output/lib/multiarch/_namemapper.so.$BUILD
fi


if [ ! -f $CWD/code/.lxml ]; then
    cd $CWD
    echo "###################"
    echo "#  Building lxml  #"
    echo "###################"
    if [ ! -f $CWD/code/.Python-host ]; then
        . build/python
    fi
    . build/lxml
    cp -avr $CWD/code/lxml-3.2.3/build/lib.linux-armv7l-2.7/lxml $CWD/output/lib/
    mv -vf $CWD/output/lib/lxml/etree.so $CWD/output/lib/multiarch/etree.so.$BUILD
    mv -vf $CWD/output/lib/lxml/objectify.so $CWD/output/lib/multiarch/objectify.so.$BUILD
fi


if [ ! -f $CWD/code/.OpenSSL ]; then
    cd $CWD
    echo "######################"
    echo "#  Building OpenSSL  #"
    echo "######################"
    if [ ! -f $CWD/code/.Python-host ]; then
        . build/python
    fi
    . build/OpenSSL
    cp -avr $CWD/code/pyOpenSSL-0.13/build/lib.linux-armv7l-2.7/OpenSSL $CWD/output/lib/
    mv -vf $CWD/output/lib/OpenSSL/crypto.so $CWD/output/lib/multiarch/crypto.so.$BUILD
    mv -vf $CWD/output/lib/OpenSSL/rand.so $CWD/output/lib/multiarch/rand.so.$BUILD
    mv -vf $CWD/output/lib/OpenSSL/SSL.so $CWD/output/lib/multiarch/SSL.so.$BUILD
fi


if [ ! -f $CWD/code/.yEnc ]; then
    cd $CWD
    echo "###################"
    echo "#  Building yEnc  #"
    echo "###################"
    if [ ! -f $CWD/code/.Python-host ]; then
        . build/python
    fi
    . build/yEnc
    cp -avr $CWD/code/yenc-0.4.0/build/lib.linux-armv7l-2.7/yenc.py $CWD/output/lib/
    cp -avr $CWD/code/yenc-0.4.0/build/lib.linux-armv7l-2.7/_yenc.so $CWD/output/lib/multiarch/_yenc.so.$BUILD
fi


if [ ! -f $CWD/code/.par2cmdline ]; then
    cd $CWD
    echo "###################"
    echo "#  Building par2  #"
    echo "###################"
    . build/par2
    cp -avr $CWD/output/par2/bin/par2 $CWD/output/lib/multiarch/par2.$BUILD
fi


if [ ! -f $CWD/code/.unrar ]; then
    cd $CWD
    echo "####################"
    echo "#  Building unrar  #"
    echo "####################"
    . build/unrar
    cp -avr $CWD/output/unrar/bin/unrar $CWD/output/lib/multiarch/unrar.$BUILD
fi


cd $CWD
echo "#####################################################"
echo "#  Installing to 'script.module.audo-dependencies'  #"
echo "#####################################################"
mkdir -p output/script.module.audo-dependencies
cp -avr $CWD/output/lib $CWD/output/script.module.audo-dependencies/
if [ ! -f $CWD/code/.Python-host ]; then
    . build/python
fi
if [ ! -f $CWD/code/.overlay ]; then
    . build/overlay
    cp -avr $CWD/code/overlay/* $CWD/output/script.module.audo-dependencies/
fi


cd $CWD
echo
. $CWD/config/cleanupenv.sh
echo
echo "####################"
echo "+++   FINISHED   +++"
echo "####################"
exit 0

