#!/bin/sh

### Set ARCH variables
export DEVICE=ARMv7
export TOOLCHAIN=$CWD/toolchain
export ARCH=armv7-a
export PATH=$TOOLCHAIN/bin:$PATH
export CFLAGS="-march=${ARCH} -mcpu=cortex-a9 -mfpu=vfpv3-d16 -mfloat-abi=hard"
export CHOST=arm-linux-gnueabihf
export CC=$TOOLCHAIN/bin/arm-linux-gnueabihf-gcc
export CXX=$TOOLCHAIN/bin/arm-linux-gnueabihf-g++
export AR=$TOOLCHAIN/bin/arm-linux-gnueabihf-ar
export RANLIB=$TOOLCHAIN/bin/arm-linux-gnueabihf-ranlib
export STRIP=$TOOLCHAIN/bin/arm-linux-gnueabihf-strip
export DEVICEAPPS=$CWD/code/ARMv7/Shares/Apps
export OUTPUTDIR=$CWD/output

### Download and install toolchain
if [ ! -f $CWD/toolchain/.arm-linux-gnueabihf ]; then
    if [ ! -f $CWD/dl/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz ]; then
        wget -P $CWD/dl/ https://releases.linaro.org/components/toolchain/binaries/latest/arm-linux-gnueabihf/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz

        if [ "$?" -ne "0" ]; then
            echo "error downloading source: $1";. $CWD/config/cleanupenv.sh;exit 1
        fi
    fi
    tar -vxf $CWD/dl/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz -C $CWD/toolchain --strip-components=1
    if [ "$?" -ne "0" ]; then
        echo "error unpacking source: $1";. $CWD/config/cleanupenv.sh;exit 1
    fi

    touch $CWD/toolchain/.arm-linux-gnueabihf
fi

echo
echo $DEVICE
echo "Toolchain: $CHOST"
echo "Location: $TOOLCHAIN"
echo
